/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Dec 29, 2013, 11:13:16 AM
 */

package src.featureextraction;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import java.io.File;
import java.net.URL;
import java.util.Collection;
import java.util.Iterator;
import java.util.ArrayList;
import net.htmlparser.jericho.Source;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author senhil
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    ArrayList al=new ArrayList();
    ArrayList pro=new ArrayList();
    ArrayList sum=new ArrayList();
     String res="";
    public MainFrame()
    {
        initComponents();
        JPanel pane=(JPanel)this.getContentPane();;
        JLabel lab=new JLabel();
        //lab.setBounds(-1,0,660,590);
        lab.setBounds(-1,0,880,660);

        lab.setIcon(new ImageIcon("image//img3.jpg"));
        //lab.setIcon(new ImageIcon("image//img2.jpg"));
        pane.add(lab);
       setDefaultLookAndFeelDecorated(true);
       setResizable(false);
       jComboBox1.setVisible(false);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Window");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Opinion Mining");

        jButton2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jButton2.setText("Extract Review");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("A Sentiment Analysis");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Nikon", "Sony" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "nikon", "Canon-digital-ixus-135","canon-ixus-510-hs","Nikon-coolpix-l820","Nikon-d5200" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Select Product");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(99, 99, 99))
        );

        setSize(new java.awt.Dimension(866, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // String input = jTextField1.getText();
   // String input= jComboBox1.getSelectedItem().toString();
     //   if(jRadioButton2.getse){
            
       // }else{
            
        //}
    String input = jComboBox2.getSelectedItem().toString();
      //input="Nikon-d5200";
        if(input.equals("")){
            JOptionPane.showMessageDialog(null, "Field Cannot be Empty", "Warning", 1);
        }//else if(input.toLowerCase().equals("nikon") || input.toLowerCase().equals("canon") ||input.toLowerCase().equals("sony")||input.toLowerCase().equals("kodak") ||input.toLowerCase().equals("fujifilm")){
            try
        {
          //  al.add(input);
     //    al.add("nikon-coolpix-l27");
          al.add("nikon");
          //  al.add("Canon");
//            al.add("FujiFilm");
 System.out.println("heba output" +al);
            ExtractReview re=new ExtractReview();
            ArrayList al1=re.getPage();
            System.out.println("review "+al1.size());
             System.out.println("heba output 8 " +al1);

             String dis="";
            int sz=al1.size();
            if(sz>10)
                sz=2;
            for(int k=0;k<sz;k++)
            //for(int k=0;k<al1.size();k++)
            {                
                //String url="http://www.testfreaks.co.in/digital-cameras/";
                String url=al1.get(k).toString();
                System.out.println(k+ "  --------------"+url);
                URL ul=new URL(url);
                Source sd=new Source(ul);
                String cc=sd.toString();
                String dd[]=cc.split("<div class=\"product-box\">");
                System.out.println(dd.length);   
                System.out.println("heba output 1" +al);
                ExtractReview er=new ExtractReview();
                int gs=dd.length;
                 if(gs>10)
                    gs=10;                 
                for(int i=0; i<gs; i++)
                //for(int i=1;i<10;i++)
                {
                    int fl=0;
                    String cl="";
                    for(int j=0;j<al.size();j++)
                    {
                        cl=al.get(j).toString();                        
                        if(dd[i].contains(cl))
                        {
                            fl=1;
                            System.out.println("---------------------- "+cl);                            
                            break;
                        }
                    }
                    
                    //System.out.println(fl);
                    if(fl==1)
                    {
                        String sm=er.extract(dd[i]);
                        if(!(sm.equals("")))
                        {
                            res=res+cl+"-->"+sm+"\n";
                            pro.add(cl);
                            sum.add(sm);
                            sm=sm.replace("@", "\n");
                            dis=dis+cl+"-->\n"+sm+"\n\n";     
                             System.out.println("Heba Output 11 " +sm); 
                        }                        
                    }
                }
               
            } 
            if(res.equals("")){
               JOptionPane.showMessageDialog(null, "Product Not Found", "Invalid Product", 2);
            }else{
                 System.out.println("Result "+res);

                ReviewFrame rf=new ReviewFrame(this);
                rf.setTitle("Review");
                rf.setVisible(true);
                rf.jTextPane1.setText(dis);  
            }
                          
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
      //  }//else{
        //    JOptionPane.showMessageDialog(null, "Product Not Found", "Invalid Product", 2);
      //  }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
